services:
  - type: web
    name: pyquotex-api
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYQUOTEX_EMAIL
        sync: false
      - key: PYQUOTEX_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: INFO
